# -*- mode: python ; coding: utf-8 -*-
# pacoca.spec — Build completo: todas as deps bundled, sem pip install no usuário final
# Uso: pyinstaller pacoca.spec --clean

block_cipher = None

_hidden = [
    # ── Módulos Pacoca (imports lazy via importlib) ─────────────────────
    "modules.system_control",
    "modules.transcription",
    "modules.summarizer",
    "modules.search",
    "modules.dev_tools",
    "modules.routines",
    "modules.productivity",
    "modules.security",
    "modules.backup",
    "modules.calendar_integration",
    "modules.reminders",
    "modules.clipboard_tools",
    "modules.screen_reader",
    "modules.meeting_detector",
    "modules.obsidian",
    "modules.web_server",
    "core.profiles",
    "core.plugin_loader",
    "input.stt",
    "input.hotkeys",
    "input.cli",
    "output.overlay",
    "output.tts",
    "output.notifier",
    "storage.context",
    "storage.db",
    "storage.file_store",
    "web.app",
    # ── uvicorn (carregado como string "web.app:app") ──────────────────
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.loops.uvloop",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.http.httptools_impl",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.protocols.websockets.websockets_impl",
    "uvicorn.protocols.websockets.wsproto_impl",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.lifespan.off",
    # ── FastAPI / Starlette ────────────────────────────────────────────
    "fastapi",
    "fastapi.middleware",
    "fastapi.middleware.base",
    "starlette",
    "starlette.middleware",
    "starlette.middleware.base",
    "starlette.responses",
    "starlette.websockets",
    "anyio",
    "anyio._backends._asyncio",
    "anyio._backends._trio",
    "anyio.streams.memory",
    # ── WebSockets ────────────────────────────────────────────────────
    "websockets",
    "websockets.legacy",
    "websockets.legacy.server",
    "h11",
    "httptools",
    # ── pyttsx3 drivers (carregados dinamicamente) ────────────────────
    "pyttsx3",
    "pyttsx3.drivers",
    "pyttsx3.drivers.sapi5",
    "pyttsx3.drivers.nsss",
    "pyttsx3.drivers.espeak",
    # ── PyQt6 (overlay) ───────────────────────────────────────────────
    "PyQt6",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    # ── STT / faster-whisper ──────────────────────────────────────────
    "faster_whisper",
    "ctranslate2",
    "pyaudio",
    "pyaudiowpatch",
    # ── Wake word / openWakeWord ───────────────────────────────────────
    "openwakeword",
    "openwakeword.model",
    "openwakeword.utils",
    # ── Google Auth ───────────────────────────────────────────────────
    "google.oauth2.credentials",
    "google.oauth2",
    "google.auth",
    "google.auth.transport.requests",
    "google_auth_oauthlib",
    "google_auth_oauthlib.flow",
    "googleapiclient",
    "googleapiclient.discovery",
    "googleapiclient.http",
    "httplib2",
    "uritemplate",
    # ── Sistema / utilitários ─────────────────────────────────────────
    "psutil",
    "pynput",
    "pynput.keyboard",
    "pynput.mouse",
    "keyboard",
    "pyautogui",
    "pyperclip",
    "pytesseract",
    "PIL",
    "PIL.Image",
    "PIL.ImageGrab",
    "plyer",
    "plyer.platforms",
    "plyer.platforms.win",
    "plyer.platforms.win.notification",
    "schedule",
    "duckduckgo_search",
    "requests",
    "multipart",
    "python_multipart",
    "yaml",
    "sqlite3",
    "win32com",
    "win32com.client",
    "pythoncom",
    "pywintypes",
]

a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("core/config.yaml",   "core"),
        ("plugins",            "plugins"),
        ("web",                "web"),
        ("hooks",              "hooks"),
    ],
    hiddenimports=_hidden,
    hookspath=["hooks"],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "scipy",
        "pandas",
        "IPython",
        "jupyter",
        "notebook",
        "pvporcupine",     # não usado; substituído por openWakeWord
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Pacoca",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Pacoca",
)
